project:
  type: website

website:
  title: "Roadway Data Decoder: AI-Powered Traffic Analysis"
  description: "Analyze data that is related to traffic enginering using Machine Learning or Artificial Intelligence and provide insights on safety and prediction accuracy."
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: master
  repo-url: https://github.com
  navbar:
    search: true

    right:
      - icon: github
        href: https://github.com

  sidebar:
    style: "docked"
    alignment: "left"
    search: true
    contents: auto
    # contents:
    # - section: "Data Analysis"
    #   contents:
    #     - ML/NumericalDataPrediction.ipynb

  page-footer: 
    left: "Copyright 2021, Ahmed Aredah" 
    right: 
      - icon: github
        href: https://github.com/AhmedAredah
      - icon: twitter 
        href: https://twitter.com/AhmedAredah 


format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-expand: 2
    max-width: 500px
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"



