---
# title: "Traffic Engineering Data Analysis Enthusiastic"
# description: "Introduction and scope of the website"
# sidebar: true
---

# Welcome to 'Roadway Data Decoder: AI-Powered Traffic Analysis'

Hello! I am **Ahmed Aredah**, a PhD student specializing in Civil Engineering with a focus on transportation. Concurrently, I'm also pursuing an MSc in Computer Science. My academic journey has equipped me with a unique blend of knowledge, bridging the gap between the worlds of transportation and computer science.

I take pride in being the developer behind [NeTrainSim](https://github.com/VTTI-CSM/NeTrainSim), an open-source network train simulator. NeTrainSim is a collaborative effort between Virginia Tech (VT), North Carolina State University (NC), and Deutsch Bahn (DB). The project was supervised and steered by the esteemed Prof. Hesham Rakha. This initiative is a testament to my passion for contributing to the community and my commitment to advancing the field of transportation through technological innovations and collaborative research.

## Scope of the Website
This platform serves as a window into my exploration of publicly available datasets related to traffic engineering. The datasets range from those focusing on safety to general traffic engineering datasets. Through comprehensive analysis, I aim to extract valuable insights, shed light on patterns, and present findings in an accessible manner. Whether you're a fellow researcher, a professional in the field, or someone with a keen interest in traffic engineering, this website offers a treasure trove of information and insights.

Feel free to dive into the analyses, and I hope you find the content both informative and enlightening!
